[package]
org = "deon"
name = "Producer"
version = "0.1.0"
distribution = "2201.12.9"

[build-options]
observabilityIncluded = true


[[platform.java11.dependency]]
groupId = "mysql"
artifactId = "mysql-connector-java"
version = "8.0.26"

[[platform.java11.dependency]]
path = "C:\\Java library\\mysql-connector\\mysql-connector-j-9.4.0.jar"